### ISSUE TITLE
Add to context menu error

### ISSUE THREAD

**Issue by neoOpus** [SamuelTulach/VirusTotalUploader#1]
Hi,

I get this error when I try to add the context menu from the settings... do you have an idea how to solve it? 

![image](https://user-images.githubusercontent.com/1388336/44295237-304b9a80-a273-11e8-9867-f79735e5ad73.png)

Thanks.

**Comment by SamuelTulach** [comment]
Have you tried running app as administrator?

As you can see there is UnauthorizedAccessException which means that the app cannot access registry.

**Comment by craigalan** [comment]
I get the same error, but when trying to run the shortcut that is in the startmenu as admin, nothing happens...where is that short cut pointing to?  The properties don't really say
![2018-08-18_105101](https://user-images.githubusercontent.com/17946784/44300420-a6341e00-a2d4-11e8-9cb7-ceb5ba7c7db7.jpg)

Also when changing to dark theme I also get an error when trying to scan...probably related to the same admin issues.
![2018-08-18_105211](https://user-images.githubusercontent.com/17946784/44300432-f1e6c780-a2d4-11e8-8ed2-aa55a887ff32.jpg)

**Comment by SamuelTulach** [comment]
Ok. So. I look into this issue and I was unable to reproduce it. Weird. I installed the app on Windows 10 in VirtualBox and no problem. Adding program to content menu also no problem (maybe you don't have admin account?). The shortcut @craigalan is looking at actually just refers to .application file (because I used integrated setup creator in Visual Studio which is crap) anyway I am going to fix it. 

@craigalan @neoOpus For now you can try to download [older version Release.zip](https://github.com/SamuelTulach/VirusTotalUploader/releases/tag/0.0.3) which contains standard binaries which you can run as administrator. After running them as administrator you should be able to add program to content menu.

@craigalan The error you are getting usually means that you have checked Dark theme in setting without adding API key (I am also gonna fix it so you don't have to reenter it everytime).

Sorry for all issues. When I get my work PC dual-boot working correctly I will push update.

**Comment by craigalan** [comment]
I am definitely admin.

**Comment by SamuelTulach** [comment]
@craigalan And running binary from link in previous response as administrator helps?

**Comment by craigalan** [comment]
About to try the other version now

**Comment by craigalan** [comment]
Nope. Same thing.

Interestingly, if I run the setup as admin, it does allow me to click add to context and it says it added it but it is not there.

But if I click the startmenu icon to run it still errors out.

**Comment by SamuelTulach** [comment]
@craigalan Can you please check if registry `HKEY_CLASSES_ROOT/*/UploaderMenuOption` is created and if it contains program path?

EDIT: Oh. Wait. My fault. You realized it should also be in `HKEY_CURRENT_USER\Software\Classes\*\shell`. Creating new version please wait.

**Comment by craigalan** [comment]
It is not there.

![2018-08-18_120730](https://user-images.githubusercontent.com/17946784/44301084-5b6bd380-a2df-11e8-9064-ef5d23eb6cdb.jpg)

**Comment by SamuelTulach** [comment]
@craigalan Can you please make screenshot of full window of UpdatedMenuOption and command?

**Comment by craigalan** [comment]
Oh....wait it is under command....I think.
![2018-08-18_122228](https://user-images.githubusercontent.com/17946784/44301227-6d4e7600-a2e1-11e8-936e-28337733e33e.jpg)

**Comment by craigalan** [comment]
Here is the full string

C:\Users\Craig\AppData\Local\Apps\2.0\TGDA9YEB.ZRH\OB8LMPXB.WN0\viru..tion_7aa9bb788a37f660_0001.0000_3109e69f9ef291b0\VirusTotal Uploader.exe %1

**Comment by craigalan** [comment]
....and I see it after a reboot.  SOOOOO YES 0.0.3 is working.
I wonder if I run the install for 0.0.4 as admin if it would work as well.  I will uninstall .3 and try that with .4

**Comment by SamuelTulach** [comment]
@craigalan Nice. Now I am gonna update the latest version to work.

**Comment by SamuelTulach** [comment]
@neoOpus How about you?

**Comment by craigalan** [comment]
I will wait for the update to .4

Also I unistalled .3 from Add/Remove program.....yet the context menu item as well as the program still exists!?

**Comment by SamuelTulach** [comment]
@craigalan The program will dissapear after reboot or after some time, but the content menu is not deleted when uninstalling, so you will have to remove it manually (pls don't kill me). Go to `HKEY_CLASSES_ROOT/*/ `and delete `UploaderMenuOption`

**Comment by craigalan** [comment]
Got it. That's not a problem. Looking forward to the update. 

Thanks for your help!

**Comment by craigalan** [comment]
How long for the program to remove...seems odd.  After a reboot it's still there.

**Comment by SamuelTulach** [comment]
@craigalan Hmmm... Probably you will need to right-click on it, select "Open file location" and remove it.

**Comment by SamuelTulach** [comment]
Also I must go now so I keep there this 0.0.4 binary if you want to use it and I will release big update later when will have time. 

[Debug.zip](https://github.com/SamuelTulach/VirusTotalUploader/files/2299703/Debug.zip)
[Release.zip](https://github.com/SamuelTulach/VirusTotalUploader/files/2299704/Release.zip)

**Comment by craigalan** [comment]
Which should we try?  Debug or Release?  What is the difference?

**Comment by SamuelTulach** [comment]
Tried to reproduce ths issue and when using 0.0.4 running setup as admin fixes it, so I am closing this issue. Next update will bring better error reporting and cleaner codebase which should make things like this dissappear, plus with new setup.
