### ISSUE TITLE
Error while scanning used context menu.

### ISSUE THREAD

**Issue by maxchu92** [SamuelTulach/VirusTotalUploader#10]
![image](https://user-images.githubusercontent.com/4240515/53072274-a92bf780-351f-11e9-8214-a2cddeed9844.png

Saw another issue post regarding context menu error, but i would like to post mine with debug message included. The error i hit seems like the folder path is not handled properly where there is a whitespace in the path. Supposingly, the path to my file should be "..\177 Attacked\ASD.cer". Clearly the path used in the program stops at 177.

**Comment by SamuelTulach** [comment]
[Should be fixed.](https://github.com/SamuelTulach/VirusTotalUploader/commit/ade6c7e78335e417ec00ae37f76379aba3620192)
