### ISSUE TITLE
What's the size limit of the public API?

### ISSUE THREAD

**Issue by e-t-l** [SamuelTulach/VirusTotalUploader#101]
The deprecated official VTuploader had a measly file size limit, and I just tried to upload a file normally to the VT website, and it says "max file size of 650 MB has been exceeded." I didn't realize the website had a file size limit. Do you know if the API has the same limit?

**Comment by JaffaCakes118** [comment]
Yes the API has the same limit.

**Comment by 3xploiton3** [comment]
in mine failed to upload 40MB files, VTU close suddenly,

it work with manual upload via chrome browser

**Comment by JaffaCakes118** [comment]
> in mine failed to upload 40MB files, VTU close suddenly,
> 
> it work with manual upload via chrome browser

Max upload size for the post endpoint is 32MB, if you want to upload bigger than that then you have to use https://developers.virustotal.com/reference/private-files-upload-url
