### ISSUE TITLE
The latest version says it's still not signed

### ISSUE THREAD

**Issue by Yaro-Maro** [SamuelTulach/VirusTotalUploader#118]
Hi,

First of all thank you so much for the program! I've just downloaded newest version, and the Microsoft Smart screen as well as my Antivirus, say that it is still not signed. (setup_any_cpu_signed.zip - 1.46MB - Dec 31, 2021)

**Comment by SamuelTulach** [comment]
Yeah I forgot about signing the setup itself. Should be fixed in the latest version now.
