### ISSUE TITLE
Product Version in File Properties does not reflect real version

### ISSUE THREAD

**Issue by GlassedSilver** [SamuelTulach/VirusTotalUploader#12]
When you inspect the .exe's file properties it will list 1.0.0.0 as both file and product version when the actual version is actually 0.0.7 according to Github.

I would advise changing the next release's version uniformly.

Side note: what's up with the folder app.publish? Is the .exe contained there unnecessary? Is it ever called? I only use the one in the main folder, would gladly keep my system nice and tidy, if it's redundant I'd like to remove it.

**Comment by GlassedSilver** [comment]
Ah, it seems you already fixed that, didn't expect someone else to be as nitpicking as I am. haha

Guess I'll just wait for a new release for that to be fixed and to have a fixed context menu uploader.

Cheers and thanks for your work!

**Comment by jiffyjoker** [comment]
also the version listed in settings hasnt changed since version 0.0.4
