### ISSUE TITLE
error vtu_settings.json

### ISSUE THREAD

**Issue by 3xploiton3** [SamuelTulach/VirusTotalUploader#120]
https://i.imgur.com/CjwmCjz.png

solved:
run vt as administrator

**Comment by SamuelTulach** [comment]
Should be fixed in the [latest update](https://github.com/SamuelTulach/VirusTotalUploader/releases/tag/0.2.1).

**Comment by maisondasilva** [comment]
@SamuelTulach I noticed that the new installer after opening the installer, it installs without asking for anything else, is this new behavior normal?
