### ISSUE TITLE
[Bug+FR] Improve handling large file sizes by using private upload url, hash search

### ISSUE THREAD

**Issue by e-t-l** [SamuelTulach/VirusTotalUploader#129]
## The problem
When trying to upload a large file, VTU stops responding. That's obviously a problem, and while it might be possible to catch errors or handle crashes more gracefully, I'm more interested in avoiding the issue in the first place by changing how VTU handles large file sizes...
### For files > 32 MB, use a private URL
[VT documentation](https://developers.virustotal.com/reference/private-files-upload-url) explains how to request a unique "private upload url" for each large file. It seem like it would be fairly straightforward for VTU to check the incoming file size, and if it's equal or greater than 32 MB, request a private upload url and send the file to that instead of the normal url.

### For files > 650(?) MB, use a hash check
My (admittedly not great) understanding of the VT API is that it still has the upper limit of 650MB per upload. So, when VTU checks the file size, if it's equal or greater than 650 MB, it should NOT upload it at all. Instead, it should generate a hash, and then search that hash on VT.

**Comment by e-t-l** [comment]
I haven't pored over the VTU codebase in detail, as my programming experience is minimal, and my C# experience is nonexistent, so please forgive me if either of these suggestions are already currently implemented. 

I can _try_ to fork VTU and make these changes myself, but again, I'd be starting from ~stackoverflow~ scratch with C#, so I can't promise any results. @SamuelTulach From the latest commits on this repo, it's unclear whether it's something you have the time or interest to continue maintaining. If you see this, could you please comment just to acknowledge it? It would be helpful to know
1. do you plan to keep working to VTU, or if we should treat it as a finished project?
2. do you think the two solutions I've described above are good ideas?

**Comment by SamuelTulach** [comment]
If the file hash is present on VT the uploader will never upload the file no matter the size. Enterprise API keys have larger upload limits. The documentation link you've provided links to API documentation for v3 while this uploader still uses v2 API endpoints. Furthermore, the [endpoint linked is available only to paid customers](https://support.virustotal.com/hc/en-us/articles/8516907790749-Private-Scanning).

**Comment by e-t-l** [comment]
Ah thank you, hadn't realized that!
