### ISSUE TITLE
The upload windows disappears without opening the webpage showing the file being analyzed

### ISSUE THREAD

**Issue by Nj6EST** [SamuelTulach/VirusTotalUploader#148]
I just started using the uploader few days ago.  It worked OK except several 'perma link not found ...' instances, but those were resolved when I tried the same file later.  however, today I tried use the uploader again, the upload window displayed uploading status, then it just disappeared rather than launching the webpage.  The file is about 50 MB.  not sure if the uploader has a size limit or not.

**Comment by SamuelTulach** [comment]
Free API is limited to 32MB only unless something has changed.

**Comment by Nj6EST** [comment]
that could be it.  thanks.
