### ISSUE TITLE
AppVeyor Builds

### ISSUE THREAD

**Issue by camjac251** [SamuelTulach/VirusTotalUploader#16]
Would it be possible to have the builds created by AppVeyor to the artifacts for download?

**Comment by SamuelTulach** [comment]
It is actually added in AppVeyor settings. I have no clue why it has stopped working. The project directories are same.

![AppVeyor settings](https://user-images.githubusercontent.com/16323119/59549223-ab94e000-8f5a-11e9-8d8a-27ab995673a2.png)

**Comment by SamuelTulach** [comment]
Closing this issue since it was associated with the old version of uploader. The entire program had [a large recode](https://github.com/SamuelTulach/VirusTotalUploader/commit/c8a8b4c44ac3705607c017e36e6b76f6fab17e48). Please reopen this issue if it persists in the new version as well.

**Comment by camjac251** [comment]
If you want to do away with Appveyor, it might be worth to try adding a GitHub action for building and uploading the artifact to releases automatically

**Comment by SamuelTulach** [comment]
[The builds are working now](https://ci.appveyor.com/project/SamuelTulach/virustotaluploader/build/artifacts). Not sure if I want to upload every commit as a new release, but I will think about it.

**Comment by camjac251** [comment]
You can set it up to only trigger builds when you add a tag for version number to a commit.

**Comment by SamuelTulach** [comment]
Took me like million attempts, but it's working now. Thanks for the tip!

**Comment by camjac251** [comment]
I was talking about Github actions. Something like this https://github.com/theChaosCoder/avsrepo/blob/master/.github/workflows/release.yml

You could use something like this with it https://github.com/microsoft/setup-msbuild
