### ISSUE TITLE
Crashes on uploading

### ISSUE THREAD

**Issue by Barafu** [SamuelTulach/VirusTotalUploader#18]
I get an error with latest version of application. When I try to upload a file, application immediately crashes. Error  happens on any file. I have double-checked that I have proper key in settings file. 

Exact error is attachment. 
![Annotation 2019-07-17 173751](https://user-images.githubusercontent.com/6612364/61385378-fa67c980-a8ba-11e9-90f6-e92562474ff0.png)

**Comment by SamuelTulach** [comment]
Can you check if nothing is blocking connection to the server? This error happens if there is an error in parsing the response from server (because it does not exist at all or because it is unusual response).

**Comment by clowrey** [comment]
I get the same exact error message.. 
Update:
Okay it worked after restarting the program after adding the API key. seems the settings don't take effect until restart.

**Comment by SamuelTulach** [comment]
> 
> 
> I get the same exact error message..
> Update:
> Okay it worked after restarting the program after adding the API key. seems the settings don't take effect until restart.

That's true. Also check if there is no space copied in the field.
