### ISSUE TITLE
Can I upload files from the linux CLI?

### ISSUE THREAD

**Issue by CholoTook** [SamuelTulach/VirusTotalUploader#19]
More a support question than an issue :-)

Thanks.

**Comment by SamuelTulach** [comment]
Sadly this is intended to be Windows GUI version of the uploader. You should be able to run it using mono and passing the file as first argument should work, but it will try to open a web browser after scan and you will not be able to get the results back as into terminal. 

If you need Linux CLI I highly recommend using some other project like [vt-cli](https://github.com/VirusTotal/vt-cli).

**Comment by CholoTook** [comment]
Thanks for this info.
