### ISSUE TITLE
Please add more options

### ISSUE THREAD

**Issue by githuborer** [SamuelTulach/VirusTotalUploader#20]
Please add ability to auto create a log file with results.
And please make option to enable/disable open in internet browser

**Comment by SamuelTulach** [comment]
I will look to some log files [in the future](https://github.com/SamuelTulach/VirusTotalUploader/commit/3b979c1815a6fcbc4c359b35dcb01c0395593f93). 

Not sure why would you like to close or open the browser but it always opens the default one.
