### ISSUE TITLE
v0.0.7 Fails to upload...

### ISSUE THREAD

**Issue by 4Jax** [SamuelTulach/VirusTotalUploader#21]
Tried latest version v0.0.7 and it produces an error box:
"Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on null reference at CallSite.Target(Closure, Callsite, Object)   it goes on-and-on.

Did notice in the program window it says v**0.0.4** ???????????????

**Comment by githuborer** [comment]
I see this sometimes too

**Comment by SamuelTulach** [comment]
Closing this issue since it was associated with the old version of uploader. The entire program had [a large recode](https://github.com/SamuelTulach/VirusTotalUploader/commit/c8a8b4c44ac3705607c017e36e6b76f6fab17e48). Please reopen this issue if it persists in the new version as well.
