### ISSUE TITLE
ErrorWindow.cs line 64

### ISSUE THREAD

**Issue by Yousha** [SamuelTulach/VirusTotalUploader#23]
In file **ErrorWindow.cs** line **64**, `OSInfo` must be changed to `SystemInfo`:

`foreach (PropertyData sp in OSInfo)`

To

`foreach (PropertyData sp in SystemInfo)`

https://github.com/SamuelTulach/VirusTotalUploader/blob/3b979c1815a6fcbc4c359b35dcb01c0395593f93/VirusTotal%20Uploader/VirusTotal%20Uploader/VirusTotal%20Uploader/ErrorWindow.cs#L64

**Comment by SamuelTulach** [comment]
Closing this issue since it was associated with the old version of uploader. The entire program had [a large recode](https://github.com/SamuelTulach/VirusTotalUploader/commit/c8a8b4c44ac3705607c017e36e6b76f6fab17e48). Please reopen this issue if it persists in the new version as well.
