### ISSUE TITLE
Problem when trying to "Reupload File"

### ISSUE THREAD

**Issue by RalfRoemling** [SamuelTulach/VirusTotalUploader#27]
![ScreenShot 929 Fatal Error](https://user-images.githubusercontent.com/12496450/77177259-80c95080-6ac5-11ea-87b2-3ef2b5fe35db.jpg)

**Comment by SamuelTulach** [comment]
Closing this issue since it was associated with the old version of uploader. The entire program had [a large recode](https://github.com/SamuelTulach/VirusTotalUploader/commit/c8a8b4c44ac3705607c017e36e6b76f6fab17e48). Please reopen this issue if it persists in the new version as well.
