### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by savchenko** [SamuelTulach/VirusTotalUploader#29]
Just checking if the project is still alive :)

ping @SamuelTulach

**Comment by SamuelTulach** [comment]
pong

**Comment by savchenko** [comment]
_...ICMP response received, starting TCP/IP transmission..._

There are [few](https://github.com/SamuelTulach/VirusTotalUploader/issues/27) [issues](https://github.com/SamuelTulach/VirusTotalUploader/issues/28) [which](https://github.com/SamuelTulach/VirusTotalUploader/issues/24) [beg](https://github.com/SamuelTulach/VirusTotalUploader/issues/21) [for](https://github.com/SamuelTulach/VirusTotalUploader/issues/22) [attention](https://github.com/SamuelTulach/VirusTotalUploader/issues/24). And 19 commits to master since v0.0.7 release.

This project is still referenced as recommended one for Windows from the [VT desktop clients](https://support.virustotal.com/hc/en-us/articles/115002179065-Desktop-Apps) webpage.


All of these make me ask &mdash; what is your plan for the VirusTotalUploader? :)

**Comment by SamuelTulach** [comment]
I had a lot of online classes recently, but I am going to work on it as soon as possible. (another online lesson is in 40 minutes dammit).

**Comment by savchenko** [comment]
Great to hear there is a plan. Take care!

**Comment by SamuelTulach** [comment]
[Started a recode.](https://github.com/SamuelTulach/VirusTotalUploader/commit/c8a8b4c44ac3705607c017e36e6b76f6fab17e48) Old version was kind of spaghetti.

**Comment by savchenko** [comment]
>  57 changed files with 69,310 additions and 0 deletions. 

_/me_ grabs popcorn.

**Comment by SamuelTulach** [comment]
*Forgets to remove the test API key from the code*

**Comment by ivandretvic** [comment]
The new release comes with 3 detections, and mainly attributed to not being digitally signed. 
https://www.virustotal.com/gui/file/68a54de865f38a00aeb1ee31ea98005330a218f959ed3517579efbc74c922a20/detection
Is there as reason you dont sign it?

**Comment by savchenko** [comment]
>  Is there as reason you dont sign it?

Certs are not free. For example, see the https://github.com/crazy-max/WindowsSpyBlocker/issues/155

**Comment by SamuelTulach** [comment]
> Is there as reason you dont sign it?

> Certs are not free. For example, see the crazy-max/WindowsSpyBlocker#155

The issue is not that it's paid. The problem is that I can't legally obtain a code signing certificate as a teen.

**Comment by savchenko** [comment]
@SamuelTulach , 

Try poking https://www.certum.eu/en/ and https://www.ksoftware.net/code-signing-certificates/
Quite literally, tell them:

1. You are a teenager
2. You are developer of the VT uploader that is currently recommended as the "official" one for MS Windows.
3. You want to sign the app, but can't do this due to your age and/or lack of funds.

Please keep this thread updated about how it goes.

**Comment by SamuelTulach** [comment]
@asvc 

Sorry for delayed response.

I don't think they can provide me a certificate simply because that would defeat the purpose of them. The certificate can either be associated with an individual person (which can't be me) or a company (which I don't have). They can't give me (as seemingly random person) certificate registered at their own company since then I could potentially leak it or do malicious stuff with it.

**Comment by savchenko** [comment]
Where have I said they will issue it in someone else's name? They can just provide one for free and advice regarding the legalities in your jurisdiction.

**Comment by SamuelTulach** [comment]
I am going to contact certum.eu, but I don't have a high hopes for that.

**Comment by CorruptComputer** [comment]
So what is going on with the releases?? I've gotten 20 release notifications today.

https://cdn.discordapp.com/attachments/725532865240236074/725800123812151436/Screenshot_20200625-155002.png

**Comment by SamuelTulach** [comment]
[AppVeyor build had an infinite loop.](https://github.com/SamuelTulach/VirusTotalUploader/commit/3f1e07158f144ab6d242000437b005b4889ecf73) Please don't kill me.

**Comment by CorruptComputer** [comment]
Ah I see, no harm done. I just thought something was weird about the rapid fire releases. Glad it's been fixed!

**Comment by SamuelTulach** [comment]
@asvc 

 

> Hello,
> 
> Certificates are issued only to adults who meet the criteria:
> 
> https://www.certum.eu/en/support/cert_expertise_tsupp_cs_requaired/
> 
> Best Regards
> Paulina Wittke
> 
> Młodszy Konsultant ds. Wsparcia Technicznego
> Pion Usług Bezpieczeństwa i Zaufania

I guess I will have to find someone with a cert that would be so nice to sign it for me.

**Comment by savchenko** [comment]
That's seriously unfortunate. Unless someone is willing to review, build and publish the application, I don't quite see a way to _"someone with a cert that would be so nice to sign it for me"_.

Wish I could help here, but realistically it might be a "Happy 18 years!" thing.

**Comment by Seithx** [comment]
Try asking Crazy Max.
https://github.com/crazy-max/WindowsSpyBlocker
Worth a try, he may be on board, maybe you can split the load, or cooperate someway, since he's also looking to sign his program.

**Comment by SodaWithoutSparkles** [comment]
[https://stackoverflow.com/questions/252226/signing-a-windows-exe-file](Would this help?) Not a pro here but wanted to help...

**Comment by SodaWithoutSparkles** [comment]
[Would this help?](https://stackoverflow.com/questions/252226/signing-a-windows-exe-file) Not a pro here but wanted to help...

**Comment by TekBear** [comment]
@SamuelTulach 
Just seeing uploader.exe as a running process is a bit generic. Have you considered changing to a more descriptive exe name like VTupload.exe or VTotalUpload.exe as it seems virustotal.com have no interest in supporting a new version.

**Comment by OnSive** [comment]
Can be closed since v0.1.9 does have a certificate and it is a new release :) @SamuelTulach
