### ISSUE TITLE
HEUR/APC

### ISSUE THREAD

**Issue by WhiteSymmetry** [SamuelTulach/VirusTotalUploader#31]
Avira Alert for 
0.0.8 setup.exe
https://www.avira.com/en/support-threats-summary/7952?track=1
![Heur](https://user-images.githubusercontent.com/5471497/81750758-c4817a80-94b6-11ea-881d-21fcc950a9a5.JPG)

**Comment by WhiteSymmetry** [comment]
https://www.virustotal.com/gui/file/68a54de865f38a00aeb1ee31ea98005330a218f959ed3517579efbc74c922a20/detection

**Comment by SamuelTulach** [comment]
False positive. You can recreate the same setup when you build it from source (release, anycpu) and use attached Inno Setup project file.

[project.zip](https://github.com/SamuelTulach/VirusTotalUploader/files/4620479/project.zip)
