### ISSUE TITLE
Typo and grammatical error in Russian localization

### ISSUE THREAD

**Issue by JeffyOLOLO** [SamuelTulach/VirusTotalUploader#33]
Typo:
"UploadForm_Info": "Инфо**р**мация файла"

And this sentence is incorrect from a grammatical point, because it means that a file owns some information, in the sense of as a thing, e.g. I have a cat. I mean this thing doesn't describe the file, it is just owned by the file.

The correct sentence is:
`"UploadForm_Info": "Информация о файле"`

**Comment by JeffyOLOLO** [comment]
Also, `"Message_Idle": "Готов"` seems to me that this's not the best translation of `Idle`. `Готов` translates as `is ready`. Maybe the problem is that `Idle` is shown before and after uploading.
Likely, translate `Idle` as `Ожидание` (`Waiting [for an action]`) would be better. 

Russian community, what do you say about this?

**Comment by SamuelTulach** [comment]
I don't know Russian. I merged the push request because in g translate it seemed good. Going to update it.

**Comment by SamuelTulach** [comment]
@TheDirectorX has updated the localization (thanks!), so it should be fine now.
