### ISSUE TITLE
Sorry, Newbie Question.  What is Uploader vs AnyCPU?

### ISSUE THREAD

**Issue by CerebralFreeze** [SamuelTulach/VirusTotalUploader#36]
Hi, Folks,

I am an ultra newbie to Github.  Just discovered this awesome website a few months ago.  I'm clueless, right?

Anyway, I notice that there is an Setup.exe in the downloadable assets as well as a folder that is labeled anycpu.  After I double-click Setup.exe, do I just delete Setup.exe and the folder anycpu?

I noticed inside the anycpu folder, there was an application called Uploader.exe.  Is this the application that I should use every day to check files?  Or, do I double-click the shortcut that was created in my start menu?

I know, I know...I'm stupid.

**Comment by SamuelTulach** [comment]
Setup.exe will automatically install the program onto your PC and copy all the required files. The anycpu.zip is just a pure build in case you want to put in on a USB drive or something.

Run the setup.exe and then just delete it and it's installed. You don't need to download anycpu.zip at all.

**Comment by CerebralFreeze** [comment]
Sorry Samuel for not getting back sooner.  I typed too many questions and I forgot about this one.  I just reinstallled my computer and I had a million questions about how to tweak it back to what it once was.  Actually, I didn't get to VirusTotal and I am finally getting to it now.  Thanks a lot for your help.  I appreciatei it!!!!!!
