### ISSUE TITLE
[Feature request} Add an entry in the file context menu

### ISSUE THREAD

**Issue by 5moufl** [SamuelTulach/VirusTotalUploader#37]
Such as the old VirusTotal tool used to do:
![screenshot example](https://i.imgur.com/DiIVVyT.png)

**Comment by NotAkitake** [comment]
You can actually do this yourself, although it would be nice to have a script run at the end of installation doing it for you:

- Open the registry editor (Run -> `regedit.msc`, or search **regedit** in start menu)
- Go to: `Computer\HKEY_CLASSES_ROOT\*\shell`
- In the left panel, **right click** on the **shell** key (folder) and create a **New -> Key**, name it `VirusTotal` for example
- In the right panel, a **default REG_SZ** (text) value is already there, **double click it** and name it what you want to see in context menus, for example `Scan with VirusTotal`
- In the left panel, **right click** on your **VirusTotal** key (folder) and create a **New -> Key**, call it `command` (mandatory name)
- In the left panel still, select this new **command** key, and in the right panel, edit the **default REG_SZ** (text) value to: `"C:\Program Files (x86)\VirusTotal Uploader\uploader.exe" "%1"`
_(quotes required - point it to the .exe of where you installed VirusTotal Uploader)_

And you're done! Then you may log out, restart, or kill explorer.exe and restart it to see the option appear when **right clicking a file**

**Optional steps**:

_To add an icon to the context menu option_:
- Go back to that **VirusTotal** key (folder) you created, and right click it, create a new **String value**, and call it `icon` (mandatory name)
- **Double click it** to set its value to: `C:\Program Files (x86)\VirusTotal Uploader\uploader.exe,0`
_(no quotes required, point to the same .exe as before and add a **,0** at the end)_

**End Result:**

![Result-VirusTotal](https://user-images.githubusercontent.com/7873528/84878800-9e896000-b08a-11ea-972e-b925bd044d4b.jpg)
![Result-Command](https://user-images.githubusercontent.com/7873528/84878796-9d583300-b08a-11ea-8073-df2afb787b4e.jpg)
![Result-ContextMenu](https://user-images.githubusercontent.com/7873528/84879233-3a1ad080-b08b-11ea-875e-1a1a6e753ea2.jpg)

**Comment by SamuelTulach** [comment]
Well it's actually created by the setup itself (or it is at least supposed to). It's not writing it to the registry, but instead it creates a shotcut so it appears under "Send to" option.

```
[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{usersendto}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}" 
```
![screenshot](https://user-images.githubusercontent.com/16323119/81683565-89e7f580-9456-11ea-9b14-def9811d779f.png)

Please reopen the issue if you can't see the the item under "Send to" submenu.
