### ISSUE TITLE
[Feature Request] Be able to upload files that don't already exist

### ISSUE THREAD

**Issue by AwesomeKalin** [SamuelTulach/VirusTotalUploader#38]
Hi all,
I want it to be possible to upload files that don't have results yet on Virustotal. That's what I thought this program did!

**Comment by AriESQ** [comment]
It sounds like you did not create a free VirusTotal API Key, and add it to VirusTotalUploader. If that works, please close this issue. 👍

https://github.com/SamuelTulach/VirusTotalUploader#how-to-get-api-key

**Comment by SamuelTulach** [comment]
The program uploads the file if it does not exist and then opens you the browser. You have to wait until it finishes analysis and then you will see the results.

**Comment by AwesomeKalin** [comment]
I have put an API key and it still doesn't work
