### ISSUE TITLE
The "Idle" text in the file upload window is not localized when you first open it

### ISSUE THREAD

**Issue by TheDirectorX** [SamuelTulach/VirusTotalUploader#43]
![image](https://user-images.githubusercontent.com/43481085/85629923-26bfc480-b68c-11ea-96f2-a6ad2f991895.png)

**Comment by SamuelTulach** [comment]
[Should be fixed now.](https://github.com/SamuelTulach/VirusTotalUploader/commit/d11f18f32d18dc24ab3568bf344a5eb6622261aa)
