### ISSUE TITLE
The localization value "Message_Saved" is truncated if it doesn't fit in the window.

### ISSUE THREAD

**Issue by TheDirectorX** [SamuelTulach/VirusTotalUploader#45]
![image](https://user-images.githubusercontent.com/43481085/85752620-ff690600-b724-11ea-8573-72ca7e248ae5.png)

### Solution options:
- Make it possible to transfer to a new line
### OR
- Change the values to "**Saved.**" https://github.com/SamuelTulach/VirusTotalUploader/blob/dab40af346376dee970fa38424567b9e1f08a576/localization/English.json#L23

**Comment by SamuelTulach** [comment]
[Or make the window larger.](https://github.com/SamuelTulach/VirusTotalUploader/commit/cbbd2ac71fb1f22e62de31eae00cb2b87de8d932)

**Comment by TheDirectorX** [comment]
**I didn't want to suggest it, because it would be too easy. ;)**
> [Or make the window larger.](https://github.com/SamuelTulach/VirusTotalUploader/commit/cbbd2ac71fb1f22e62de31eae00cb2b87de8d932)
