### ISSUE TITLE
Unable to drag&drop file into the program

### ISSUE THREAD

**Issue by Yousha** [SamuelTulach/VirusTotalUploader#49]
I'm not able to drag&drop files into the program's window and nothing happens. (cursor icon is `No`)
Even in recompiled version.

Uploader 1.0.110 setup
Windows 10 64bit 1909
.Net Framework 4.7.2 64bit
x64 CPU Intel

**Comment by SamuelTulach** [comment]
Should be fixed now. It was probably happening, because Windows has a stupid default settings that does not allow drag & drop to programs running as admin (or as different user).
