### ISSUE TITLE
Unable to scan executable files from context menu due to error

### ISSUE THREAD

**Issue by zypA13510** [SamuelTulach/VirusTotalUploader#5]
![image](https://user-images.githubusercontent.com/8077540/48323296-80fe4400-e666-11e8-8f49-6dc72757bca0.png)

## Setup
1. Downloaded `Release.zip`
2. Extract to `%LocalAppData%\Programs\VirusTotal Uploader`
3. Run `VirusTotal Uploader.exe` as administrator
4. Open settings, enter API key, save settings.
5. Add to context menu, and then close VirusTotal Uploader
6. Try scanning exe files from context menu

------
A few exe files can be scanned without error, but I can't figure out what's special about them.
And for those causing the error, drag-n-drop them into the main window does not cause this error.

**Comment by SamuelTulach** [comment]
Can you please try this version and post error log from this version?
[Debug.zip](https://github.com/SamuelTulach/VirusTotalUploader/files/2572603/Debug.zip)

**Comment by Zhangsun321** [comment]
I have same problem... here is the report  extracted.. ran as admin... added api... added to context menu..   

OS Info: BootDevice : \Device\HarddiskVolume1
BuildNumber : 17134
BuildType : Multiprocessor Free
Caption : Microsoft Windows 10 Home
CodeSet : 1252
CountryCode : 1
CreationClassName : Win32_OperatingSystem
CSCreationClassName : Win32_ComputerSystem
CSDVersion : 
CSName : LAPTOP-VR0PB2Q1
CurrentTimeZone : -300
DataExecutionPrevention_32BitApplications : True
DataExecutionPrevention_Available : True
DataExecutionPrevention_Drivers : True
DataExecutionPrevention_SupportPolicy : 2
Debug : False
Description : 
Distributed : False
EncryptionLevel : 256
ForegroundApplicationBoost : 2
FreePhysicalMemory : 2329216
FreeSpaceInPagingFiles : 7658484
FreeVirtualMemory : 6571944
InstallDate : 20180908191023.000000-300
LargeSystemCache : 
LastBootUpTime : 20181107161429.500000-300
LocalDateTime : 20181112194631.144000-300
Locale : 0409
Manufacturer : Microsoft Corporation
MaxNumberOfProcesses : 4294967295
MaxProcessMemorySize : 137438953344
MUILanguages : System.String[]
Name : Microsoft Windows 10 Home|C:\WINDOWS|\Device\Harddisk0\Partition3
NumberOfLicensedUsers : 
NumberOfProcesses : 229
NumberOfUsers : 2
OperatingSystemSKU : 101
Organization : 
OSArchitecture : 64-bit
OSLanguage : 1033
OSProductSuite : 768
OSType : 18
OtherTypeDescription : 
PAEEnabled : 
PlusProductID : 
PlusVersionNumber : 
PortableOperatingSystem : False
Primary : True
ProductType : 1
RegisteredUser : 
SerialNumber : 00325-95800-00000-AAOEM
ServicePackMajorVersion : 0
ServicePackMinorVersion : 0
SizeStoredInPagingFiles : 8276896
Status : OK
SuiteMask : 784
SystemDevice : \Device\HarddiskVolume3
SystemDirectory : C:\WINDOWS\system32
SystemDrive : C:
TotalSwapSpaceSize : 
TotalVirtualMemorySize : 16553792
TotalVisibleMemorySize : 8276896
Version : 10.0.17134
WindowsDirectory : C:\WINDOWS

System Info: BootDevice : \Device\HarddiskVolume1
BuildNumber : 17134
BuildType : Multiprocessor Free
Caption : Microsoft Windows 10 Home
CodeSet : 1252
CountryCode : 1
CreationClassName : Win32_OperatingSystem
CSCreationClassName : Win32_ComputerSystem
CSDVersion : 
CSName : LAPTOP-VR0PB2Q1
CurrentTimeZone : -300
DataExecutionPrevention_32BitApplications : True
DataExecutionPrevention_Available : True
DataExecutionPrevention_Drivers : True
DataExecutionPrevention_SupportPolicy : 2
Debug : False
Description : 
Distributed : False
EncryptionLevel : 256
ForegroundApplicationBoost : 2
FreePhysicalMemory : 2329216
FreeSpaceInPagingFiles : 7658484
FreeVirtualMemory : 6571944
InstallDate : 20180908191023.000000-300
LargeSystemCache : 
LastBootUpTime : 20181107161429.500000-300
LocalDateTime : 20181112194631.144000-300
Locale : 0409
Manufacturer : Microsoft Corporation
MaxNumberOfProcesses : 4294967295
MaxProcessMemorySize : 137438953344
MUILanguages : System.String[]
Name : Microsoft Windows 10 Home|C:\WINDOWS|\Device\Harddisk0\Partition3
NumberOfLicensedUsers : 
NumberOfProcesses : 229
NumberOfUsers : 2
OperatingSystemSKU : 101
Organization : 
OSArchitecture : 64-bit
OSLanguage : 1033
OSProductSuite : 768
OSType : 18
OtherTypeDescription : 
PAEEnabled : 
PlusProductID : 
PlusVersionNumber : 
PortableOperatingSystem : False
Primary : True
ProductType : 1
RegisteredUser : 
SerialNumber : 00325-95800-00000-AAOEM
ServicePackMajorVersion : 0
ServicePackMinorVersion : 0
SizeStoredInPagingFiles : 8276896
Status : OK
SuiteMask : 784
SystemDevice : \Device\HarddiskVolume3
SystemDirectory : C:\WINDOWS\system32
SystemDrive : C:
TotalSwapSpaceSize : 
TotalVirtualMemorySize : 16553792
TotalVisibleMemorySize : 8276896
Version : 10.0.17134
WindowsDirectory : C:\WINDOWS


There is no valid response from VirusTotal. Please check if your internet connection, API key and firewall.
OE: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at VirusTotal_Uploader.Form1.<UploadFile>b__12_1(IRestResponse response) in C:\Users\samtu\Source\Repos\SamuelTulach\VirusTotalUploader\VirusTotal Uploader\VirusTotal Uploader\VirusTotal Uploader\Form1.cs:line 182

**Comment by waldens** [comment]
Same issue here. Sample exe: https://github.com/AucT/AucT-Hotkeys-Tool/releases/download/v2.9.11/AHT.v2.9.11.exe
![](https://i.loli.net/2018/11/13/5bea5c875c198.png)

Seems that when the exe is running and uploading by VirusTotalUploader, the error will occur. Whereas if not running when being uploaded, everything works well, at least for this sample file.

VirusTotalUploader 0.0.7 + win7x64

**Comment by zypA13510** [comment]
@waldens 
> Seems that when the exe is running and uploading by VirusTotalUploader, the error will occur. Whereas if not running when being uploaded, everything works well, at least for this sample file.

I have the same thought at first, but later I've found several exe files (tested `7zFM.exe` - the GUI for 7-Zip) not running but failed to upload. So I think this is not the cause, or at least not the only cause.

**Comment by SamuelTulach** [comment]
I am testing this issue. It is right that it happens when you have file opened. I just added check for file read access. The problem is that now I can´t contact official API even with their example python commands. Maybe it´s down now? I am trying to fix it. Thank you for your reports. If you find something else interesting tell me.

![screenshot2](https://user-images.githubusercontent.com/16323119/48422577-40362600-e75f-11e8-8239-8d2325f6af93.png)


Edit: Even official API documentation is not working correctly.

![screeenshot3](https://user-images.githubusercontent.com/16323119/48423448-e9315080-e760-11e8-9256-cf9f23850fbb.png)

**Comment by zypA13510** [comment]
@SamuelTulach I'm not sure if it's you hitting the rate-limit? At the moment I can still use the app, only not from context menu. From VirusTotal website:

Parameter | Setting
-- | --
Privileges | public key
Request rate | 4 requests/minute
Daily quota | 5760 requests/day
Monthly quota | 178560 requests/month

And it says you can get more requests with a private API key.

**Comment by SamuelTulach** [comment]
@zypA13510 Thank you. I know about the limit, but no I am not hitting it. I even tried diffrent API keys and the server is not responding even on my VPS server. It´s really weird. I contacted VirusTotal support and they checked my key, the result is that it should work with no problem. Weird.

**Comment by StrollStars** [comment]
I had the same error. I didn't add to context menu and enter API key, but I don't think that's the point.

**Comment by SamuelTulach** [comment]
Probably fixed by #15.
