### ISSUE TITLE
Webroot deletes uploader.exe

### ISSUE THREAD

**Issue by cyraxote** [SamuelTulach/VirusTotalUploader#50]
Webroot labels uploader.exe as [W32.Adware.Gen] and then deletes it. I assume I have to add it to the exception list?

**Comment by SamuelTulach** [comment]
Sadly yes. Honestly I have no clue what can be triggering the adware warning (maybe the name VirusTotal Uploader?), but it may also be because of the absence of code signing certificate (see #29)
