### ISSUE TITLE
too many steps

### ISSUE THREAD

**Issue by Entwineo** [SamuelTulach/VirusTotalUploader#53]
hey. i download anycpu.zip i created shortcut in my sendto folder to easily scan file with virustotal. whenever i send file to the application it only show me Hash values and an option to upload, and the window of app stays after virustotal web page.. please make it simple.
file>uploader>virustotalwebpage or detection values(2/71)

**Comment by SamuelTulach** [comment]
[Added option for direct upload.](https://github.com/SamuelTulach/VirusTotalUploader/commit/e1f50eb57f85c7b6fbc6d77bbb6883f86f431b39)
