### ISSUE TITLE
build for dotnet 4.6

### ISSUE THREAD

**Issue by TekBear** [SamuelTulach/VirusTotalUploader#55]
dotnet 4.7 is not supported on older OS versions would this compile under dotnet 4.6. I don't know how to build a dotnet application but willing to try if there is a how 2 guide.

**Comment by SamuelTulach** [comment]
[Done.](https://github.com/SamuelTulach/VirusTotalUploader/commit/03b13e441c01db4e8c80af22c07a56e98127ea08)

**Comment by TekBear** [comment]
@SamuelTulach  thank you.
