### ISSUE TITLE
"Open settings" and EXE name

### ISSUE THREAD

**Issue by TekBear** [SamuelTulach/VirusTotalUploader#57]
"Open settings" button has wrong argument:
`"C:\Windows\explorer.exe" /e, /select, "C:\yourpath\\vtu_settings.json"`
it needs to be 
`"C:\Windows\explorer.exe" /e, /select, "C:\yourpath\vtu_settings.json"`

BTW, just seeing uploader.exe as a running process is a bit generic. as it seems virustotal.com have no interest in supporting a new version.  Have you considered changing to a more descriptive EXE name like VTupload.exe or VTotalUpload.exe (yes I do know I can do it manually ) ?

My typical use case is using via "send to" menu + uploader.exe. I appreciate window closes automatically after upload that was a feature the other virustotal2.exe did not have.

**Comment by SamuelTulach** [comment]
[Fixed now](https://github.com/SamuelTulach/VirusTotalUploader/commit/b1bd5d42c1e87d4339f91d3aaa5454be00077a84).
