### ISSUE TITLE
3/69 virus engines flagged VTU

### ISSUE THREAD

**Issue by jasonbrown1965** [SamuelTulach/VirusTotalUploader#58]
Hi there, 

VirusTotal [detects](https://www.virustotal.com/gui/file/7e52bf91368340d412c9606ef8a0910ff382454b082de246ddb482c38c678ed6/detection) this as malicious:

![image](https://user-images.githubusercontent.com/11400799/92226890-8a226a00-eef9-11ea-939d-417dea229998.png)

Kind of weird, considering I got here from [VirusTotal itself](https://support.virustotal.com/hc/en-us/articles/115002179065-Desktop-apps). Probably false positive but needs to be looked at for any security flaws and general public trust aspects. Local Malwarebytes scan didn't find anything.

**Comment by SamuelTulach** [comment]
As it was discussed before, those warnings are mostly caused by the fact, that there is no codesigning certificate. I don't have a problem buying one, I am just not legally allowed to (as a teen). My friend will be getting OV codesigning certificate, so he might be signing the builds in the future.

**Comment by jasonbrown1965** [comment]
Ah gotcha, sorry about that.

Thanks for getting back, and what a pain being legally barred. A pity if there is not some youth innovation channel that might make it possible somehow. Thanks again.
