### ISSUE TITLE
Typo in window title

### ISSUE THREAD

**Issue by hyzor** [SamuelTulach/VirusTotalUploader#59]
Hi, great app, but one thing that annoys me is the typo in the window title "VirusTotal Uploder", when it should be "VirusTotal Uploader". Just a minor thing. Keep up the good work!

![image](https://user-images.githubusercontent.com/4078483/92303793-98fc3180-ef78-11ea-850f-e1f90b37a57d.png)

**Comment by TekBear** [comment]
I never noticed that :-)

**Comment by SamuelTulach** [comment]
The change was merged. Closing issue.
