### ISSUE TITLE
Found malicious in "uploader.exe"

### ISSUE THREAD

**Issue by karloti** [SamuelTulach/VirusTotalUploader#61]
### 3 engines detected this file
- SecureAge APEX : Malicious
- SentinelOne (Static ML) : DFI - Suspicious PE
- CrowdStrike Falcon : Win/malicious_confidence_60% (W) 

MD5	6e491549712689002f9027b91b719291
SHA-1	fd85fdd7d77d40b574d1279aafbbc9d40eba027e
SHA-256	7e52bf91368340d412c9606ef8a0910ff382454b082de246ddb482c38c678ed6
File type	Win32 EXE
File size	1.83 MB (1921395 bytes)

Creation Time	2019-04-27 08:22:11
First Submission	2020-08-21 12:59:25
Last Submission	2020-09-13 05:51:12
Last Analysis	2020-09-16 22:46:54

[https://www.virustotal.com/gui/file/7e52bf91368340d412c9606ef8a0910ff382454b082de246ddb482c38c678ed6/details](url)

**Comment by SamuelTulach** [comment]
#58 #52 #50

Missing code signing certificate. Sadly can't do anything about that. #29
