### ISSUE TITLE
Open settings file button only opens This PC

### ISSUE THREAD

**Issue by The-SamminAter** [SamuelTulach/VirusTotalUploader#63]
I am using the latest release, v1.0.121.

In the `more` section, the `Open settings file` button just opens a new Windows Explorer window at the path `This PC`.

**Comment by SamuelTulach** [comment]
[Should be fixed now](https://github.com/SamuelTulach/VirusTotalUploader/commit/b1bd5d42c1e87d4339f91d3aaa5454be00077a84).
