### ISSUE TITLE
re-uploading the file doesn't

### ISSUE THREAD

**Issue by yaronelh** [SamuelTulach/VirusTotalUploader#64]
clicking there re-upload (Sometimes even sending the file regularly) file button doesn't work it opens a page that is not functional

https://i.imgur.com/tKJAVqV.png

**Comment by SamuelTulach** [comment]
You have to wait until the analisys are complete and then reload the page.

**Comment by yaronelh** [comment]
I see, thanks
Is there a way of doing that through the command line?

Also when I try to send the file through the command line I get an error like this
VirusTotalUploader2.2.exe E:\G_Suite\Personal Projects\Desktop Software\fix file\fix Freezing file\Output\fix Freezing Fix Installer.exe


VirusTotal Uploader 2.2-beta
VirusTotal Uploader 2.2-beta is able to upload only 5 files at most, sorry

**Comment by SamuelTulach** [comment]
You need to put the file in a quotes like so:
`VirusTotalUploader2.2.exe "E:\G_Suite\Personal Projects\Desktop Software\fix file\fix Freezing file\Output\fix Freezing Fix Installer.exe"`

**Comment by yaronelh** [comment]
is there a way to requested immediately as a re-upload/rescan?

**Comment by yaronelh** [comment]
is there a way to requested immediately as a re-upload/rescan?

**Comment by leao-nardo** [comment]
> is there a way to requested immediately as a re-upload/rescan?

theres a "  "Direct file upload", which will bypass the info window.  "in the option as the dev says in issue #73 . maybe if you mark that will rescan right away. you could test it (i use older version without this option)
