### ISSUE TITLE
Malware Detected

### ISSUE THREAD

**Issue by daledali** [SamuelTulach/VirusTotalUploader#66]
Is this a false positive. If it is, there should be a warning in the read.me.

![image](https://user-images.githubusercontent.com/51318912/101295742-60b4fb00-37d4-11eb-9f0f-4fd2449d34ea.png)

**Comment by SamuelTulach** [comment]
Sadly it is a false positive. Most likely it does not like the fact that it does not have a code signing certificate and it's a self-extracting setup.

**Comment by daledali** [comment]
Thanks
