### ISSUE TITLE
Trailing space from VirusTotal gives 64 error + solution

### ISSUE THREAD

**Issue by jasonbrown1965** [SamuelTulach/VirusTotalUploader#67]
What I expected to happen:
To be able to drop-and-drag a file onto VTU and have it checked for malware 

What happened:
Returned an error referring to API key having to be 64 characters.

Replication:
Error returns on provided API key and new key from login to VirusTotal web.

Solution:
Copying API key into text editor and deleting trailing extra (empty) space from end of key, then selecting, copying and pasting _key only_ (no empty space at end) into VTU settings box for API, under "More" from main screen.

**Comment by SamuelTulach** [comment]
[API key input should now be trimmed](https://github.com/SamuelTulach/VirusTotalUploader/commit/1ac138a121a7c9d7e0b93e42c63b5cad2c9d3b6d).
