### ISSUE TITLE
URL not found error in VT results 

### ISSUE THREAD

**Issue by jasonbrown1965** [SamuelTulach/VirusTotalUploader#68]
What I expected to happen:
Uploader would open scan results on VirusTotal website.

What happened: 
A scan result page flashes briefly before auto-switching to URL not found.

Replication:
Three repeated attempts produced same result. 

On Win10/64 updates, malware checked etc

**Comment by SamuelTulach** [comment]
Does the issue still persist and if it does, does it happen only on certain files?

**Comment by phitewower** [comment]
The problem still persists.
This happens when you scan a file that has not yet been scanned. The browser opens the Item not found page.
For example, zip a file and send it through the program. In most cases - Item not found page.

For those files that were scanned earlier, a page with scan results opens.

**Comment by SamuelTulach** [comment]
Sorry for (really) late response. Can you upload an example file to some file sharing service so I can try to reproduce it. Also didn't the results show up after some time after file upload? It's possible the server just didn't start processing it yet.

**Comment by kotenok2000** [comment]
I updated to the latest release  and it worked.

**Comment by zekaka** [comment]
I have exactly the same problem that phitewower describes. Uploading a file to Virustotal that is still unknown there, I get the error message "item not found". I use the the newest version of Virustotal Uploader: uploader-v1.0.128.
![vtl+](https://user-images.githubusercontent.com/63443504/124509181-c81a4400-ddd1-11eb-9e11-c92d854652cc.jpg)

**Comment by SamuelTulach** [comment]
> 
> 
> I have exactly the same problem that phitewower describes. Uploading a file to Virustotal that is still unknown there, I get the error message "item not found". I use the the newest version of Virustotal Uploader: uploader-v1.0.128.
> ![vtl+](https://user-images.githubusercontent.com/63443504/124509181-c81a4400-ddd1-11eb-9e11-c92d854652cc.jpg)

Could you possibly try to rescan the file after few minutes? Maybe the link is not valid until the first scan starts. In such a case, I would have to add another form that would wait for the results and then display them.

**Comment by zekaka** [comment]
A rescan some minutes later works ...

**Comment by zekaka** [comment]
So, it would be perfect, if you could implement a "form that would wait for the results and then display them".  :-)

**Comment by SamuelTulach** [comment]
I will look into it, will post here when there are any updates.

**Comment by zekaka** [comment]
Thank you!

**Comment by SamuelTulach** [comment]
I wanted to look at it right now, but it seems like VirusTotal have yet again decreased their API limits. 

![image](https://user-images.githubusercontent.com/16323119/124776701-ef8f1f00-df3f-11eb-85e6-dd0b62f6c1f7.png)

Made a single request and now I can't test it anymore :/

I guess I will have to contact them and ask for a premium API key...

**Comment by SamuelTulach** [comment]
Alright, got it sorted out with a support. [This push should fix it](https://github.com/SamuelTulach/VirusTotalUploader/commit/61ed57a1458925fa2c305debb384a32d1f23c33b). New update is going to be pushed out as soon as AppVeyor finishes the build. I am going to close this issue for now, if the issue reoccurs with the latest update, let me know.
