### ISSUE TITLE
VirusTotal Detected virus on VirusTotalUploader! 

### ISSUE THREAD

**Issue by abusayed0206** [SamuelTulach/VirusTotalUploader#72]
Why it detects virus by 3 engine? 

https://www.virustotal.com/gui/file/0747779e204466363acba9255bf8257ecce072748e4fff8668ec0338671a64c5/detection

**Comment by SamuelTulach** [comment]
If you look at the detections, all of them are only suspicions and related to the fact that it's a self-extracting archive. Another issue is missing code signing certificate which I can't unfortunately get right now. It's a false positive. 

If you want to be 100% sure, you can build it from source. InnoSetup project file is also included. Also please note that those builds are uploaded by AppVeyor so they are build directly from this repo.

**Comment by abusayed0206** [comment]
Tnx for your reply. I've also checked by my antivirus(Mcafee). It seemed clean!  

Tnx again.
