### ISSUE TITLE
Necessary improvements

### ISSUE THREAD

**Issue by Ahplla** [SamuelTulach/VirusTotalUploader#73]
### Necessary improvements

In the original official version of the Virustotal Uploader for Desktop (and it still is) very very simple, a right click will go directly to the website. It automatically opens the website with the file analysis page.
![image](https://user-images.githubusercontent.com/16189267/112058673-a30f0780-8b39-11eb-9ea5-618050095420.png)

The right click appears right at the beginning, not "send to"
![image](https://user-images.githubusercontent.com/16189267/112058950-fda86380-8b39-11eb-9ae8-21be5b669175.png)

In the Samuel Tulach version, two steps are required:
![image](https://user-images.githubusercontent.com/16189267/112059093-2fb9c580-8b3a-11eb-90f8-44c81522114d.png)

In the Samuel Tulach version a window appears with the file hash that is useless, I believe for 99% of people, a window that does nothing automatic. It doesn't open anything automatically.
![image](https://user-images.githubusercontent.com/16189267/112058032-d00eea80-8b38-11eb-84f3-43c9fae48a58.png)

I hope that these two points have been clear and understandable.

**Comment by SamuelTulach** [comment]
You can check "Direct file upload", which will bypass the info window. I personally prefer having the program in "Send to" submenu (otherwise the context menu becomes very bloated), but if you really want to add it into the main context menu, you can manually [create a registry entry](https://www.groovypost.com/howto/add-any-program-windows-context-menu/).

**Comment by leao-nardo** [comment]
you could leave both option in the settings , btw ,the code is already done. 

so in the settings can have options "add to context menu" and "add to send to menu" . 

and in the "Direct file upload", which will bypass the info window. could be added a "direct open result page" to bypass this and open the hash result without reuploading
