### ISSUE TITLE
Add a context menu to quickly upload a file

### ISSUE THREAD

**Issue by ayoubfaouzi** [SamuelTulach/VirusTotalUploader#81]
Hi @SamuelTulach 

I find it very practical to add something like this:

![image](https://user-images.githubusercontent.com/5129564/129674390-03a5c8fb-86c3-4a80-8cab-f0f82d983e14.png)

Cheers.

**Comment by SamuelTulach** [comment]
#70

**Comment by ayoubfaouzi** [comment]
Thanks !
