### ISSUE TITLE
App version 0.0.7 is marked as 0.0.4

### ISSUE THREAD

**Issue by baMain** [SamuelTulach/VirusTotalUploader#9]
In the app it self:

![image](https://user-images.githubusercontent.com/22710333/52869578-a52e5d00-314e-11e9-89c7-196e202d0d09.png)

and in the Properties:
![image](https://user-images.githubusercontent.com/22710333/52869658-d73fbf00-314e-11e9-91c0-e5fb3cc16faf.png)

**Comment by SamuelTulach** [comment]
Fixed with [7825c40](https://github.com/SamuelTulach/VirusTotalUploader/commit/250e3d654ae0cd5f9f8bea2342732b43734ed62b) and [250e3d6](https://github.com/SamuelTulach/VirusTotalUploader/commit/53614bb8ddca0ebadbf5ff3eef344656b6661cfa). Thank you for report!
