### ISSUE TITLE
Feature Request: Context Menu

### ISSUE THREAD

**Issue by CreativiTimothy** [SamuelTulach/VirusTotalUploader#93]
Hi, the app is great and I don't have any problems with it. It would be nice if a context menu could be added. The old Virus Total Desktop Uploader had it which made upload a little bit faster. Not a big deal but would be nice

**Comment by tnhung2011** [comment]
That's a great feature request. I hope Samuel notice (and not busy too).

**Comment by SamuelTulach** [comment]
#81 #70 #37

**Comment by SamuelTulach** [comment]
I [have moved the context menu entry](https://github.com/SamuelTulach/VirusTotalUploader/commit/a0347b990342f3644edc161d42f54056a5ac58ac) which will be on top of the context menu now. 

![image](https://user-images.githubusercontent.com/16323119/141642322-9c3dfa37-a242-4d11-97d6-bd03d73bcec0.png)

Hopefully this will stop the confusion. Will be in the next release.

**Comment by madmax2** [comment]
@SamuelTulach when is this feature coming out?
I am using version 0.2.1.

also can you add the virustotal icon to that context menu?
It will help us in quickly identifying the menu item in the context menu
