### ISSUE TITLE
Uploader-v1.0.155 Integrate with the Windows 11 Context Menu

### ISSUE THREAD

**Issue by maisondasilva** [SamuelTulach/VirusTotalUploader#95]
For some reason the new version is not creating the shortcut in shell:sendto (C:\Users\XXXX\AppData\Roaming\Microsoft\Windows\SendTo)

Installing the previous version the shortcut is created, removing and installing the new version is not created. 

@SamuelTulach I saw that the shortcut was created in the shell, is it possible to make this menu appear in the new shell menu of Windows 11? Same Winrar?

Example https://github.com/microsoft/vscode/issues/127365
https://blogs.windows.com/windowsdeveloper/2021/07/19/extending-the-context-menu-and-share-dialog-in-windows-11/

Another option https://www.howtogeek.com/howto/windows-vista/add-take-ownership-to-explorer-right-click-menu-in-vista/

https://github.com/microsoft/vscode/issues/127365#issuecomment-945140679

Example for Windows 11

![image](https://user-images.githubusercontent.com/11423362/141854831-b1b8579a-aeb7-4142-b3a1-d1aff377f535.png)

**Comment by maisonmdsgreen** [comment]
@SamuelTulach

**Comment by maisondasilva** [comment]
@SamuelTulach https://github.com/ikas-mc/ContextMenuForWindows11

**Comment by tnhung2011** [comment]
@maisonmdsgreen It could be an Inno Setup issue (https://github.com/SamuelTulach/VirusTotalUploader/issues/90#issuecomment-967970103). @SamuelTulach should change the installer.

**Comment by maisondasilva** [comment]
@tnhung2011 I was reporting a problem but I saw that it's ok and just a Windows bug, but it would be nice to implement it in Windows 11 in the new menu, I gave some links with important information

**Comment by SamuelTulach** [comment]
New version is creating a registry entry to create a command directly in the shell menu (the shortcut in "Send To" was confusing for many people and there were tens of issues regarding no context menu entry). 

![image](https://user-images.githubusercontent.com/16323119/141957498-9b49df60-40ef-4c97-bb79-726441d854e7.png)

Unfortunately Windows 11 changed the context menu but because they are autistic, you can still access the old menu by selecting "More Options" in the new menu, which should get you to the old one where you should have "Upload to VirusTotal" entry.

I will try to look into it to figure out how to put it into the new menu, but I was not able to find any official documentation regarding it (only for the old one).

**Comment by maisondasilva** [comment]
The links I posted above if you can take a look.  See that in the example image I managed to create in the new menu, the winrar I managed to make it work, I just don't know how.

**Comment by SamuelTulach** [comment]
> 
> 
> The links I posted above if you can take a look. See that in the example image I managed to create in the new menu, the winrar I managed to make it work, I just don't know how.

Using a hack to add/replace the "execute as" item in context menu is definitely not the way I want to go. Windows 11 will probably require sparse manifests and the IExplorerCommand which effectively means that I will have to write a custom installer for VT uploader or implement the context menu integration in the program itself, but that would mean it won't get removed after uninstalling.

**Comment by maisondasilva** [comment]
@SamuelTulach I talked to the Winrar Developer he sent me this. 

Hello,

I used this one:
https://github.com/microsoft/AppModelSamples/tree/master/Samples/SparsePackages

as a sample.

First, you need to implement the shell extension using
IExplorerCommand interface. IContextMenu is included only to
"Show more options" menu in Windows 11.

Then you need to package this shell extension to .msix file,
sign this file with digital signature and install this .msix package
from another app.

Overall it is complicated and troublesome. I spent about two months
to implement this and still searching for workarounds for some issues.

Eugene

**Comment by SamuelTulach** [comment]
> 
> 
> @SamuelTulach I talked to the Winrar Developer he sent me this.
> 
> Hello,
> 
> I used this one: https://github.com/microsoft/AppModelSamples/tree/master/Samples/SparsePackages
> 
> as a sample.
> 
> First, you need to implement the shell extension using IExplorerCommand interface. IContextMenu is included only to "Show more options" menu in Windows 11.
> 
> Then you need to package this shell extension to .msix file, sign this file with digital signature and install this .msix package from another app.
> 
> Overall it is complicated and troublesome. I spent about two months to implement this and still searching for workarounds for some issues.
> 
> Eugene

If I had codesigning signature that would be nice. I was told by Sectigo that I need notary to verify myself.

**Comment by maisondasilva** [comment]
I saw that you now have a certificate and I also saw that Microsoft has been changing something else to make it easier.

https://twitter.com/JenMsft/status/1494539819346583557?s=20&t=1ob0CxTx8G5l9X6r1zXKjw

https://blogs.windows.com/windowsdeveloper/2021/07/19/extending-the-context-menu-and-share-dialog-in-windows-11/

@SamuelTulach

**Comment by maisondasilva** [comment]
Congrats on the certificate. @SamuelTulach

**Comment by SamuelTulach** [comment]
The latest version uses a different setup creator with an option for the menu entry. Installing a sparse package myself would be a pain in the ass.

![win11](https://user-images.githubusercontent.com/16323119/219900618-d81b8f4b-6f9a-468b-bab1-5fd5b5e9fa02.png)

**Comment by maisondasilva** [comment]
Nice version!

**Comment by modz2014** [comment]
there is no other way to use the shell context menu in windows 11 new one
